## Site metadata ##

title: Jekyll Actions Guide
description: How to setup GH Pages + GH Actions for use with Jekyll 4

### Built settings ###

url: "https://michaelcurrin.github.io"
baseurl: "/jekyll-actions-quickstart"

github_username: MichaelCurrin

theme: minima
