## Site metadata ##

title: Jekyll Actions Guide
description: How to setup GH Pages + GH Actions for use with Jekyll 4

### Built settings ###

url: "https://vikrantcue.github.io"
baseurl: "/test"

github_username: vikrantcue

theme: minima
